### ISSUE TITLE
evaluate middlewares

### ISSUE THREAD

**Issue by fponticelli** [fponticelli/restx#10]
[middleware](http://expressjs.com/resources/middleware.html)
- [x] body parser
- [x] compression
- [x] cookie-parser
- [x] cookie-session
- [ ] csrf
- [ ] error handler
- [ ] express debug
- [ ] partial response?
- [ ] session
- [ ] cdn ?
- [x] slash ?
- [x] uncapitalize ? case sensitive?
- [ ] method override
- [x] logging (morgan)
- [ ] response time
- [x] favicon
- [ ] index
- [x] static
- [ ] vhost ?
- [ ] view helpers
- [ ] multipart
- [ ] query string
- [ ] static cache
- [ ] expose https://github.com/expressjs/express-expose
- [ ] flash message https://github.com/expressjs/flash
- [ ] image optimizer https://github.com/msemenistyi/connect-image-optimus

**Comment by theRemix** [comment]
this sounds like some notes for yourself, though i am interested in possibly contributing.
are these middlewares that you want to explore how they would work with restx, or are you thinking about making restx adopt an express style middleware pattern?

**Comment by fponticelli** [comment]
restx is completely built on top of express so I would like to reuse all the goodness the express community provides with no changes. So the first step will be to just be able to add any middleware easily. The second one will be to "type" those middlewares so that they are more haxe oriented where it makes sense. Third step take advantage of haxe meta to interact with the middleware.
@mlms13 is already working in improving HTTP methods using meta.

**Comment by fponticelli** [comment]
In any case, any suggestion/PR is always very well received.

**Comment by theRemix** [comment]
i'll do what i can.
once you decide how they will be integrated, i can help create externs and test middleware as i use them.

**Comment by fponticelli** [comment]
Sure thing, we should have some changes in by tomorrow including some light middleware introduction.

**Comment by fponticelli** [comment]
And by the way we should move the externs to an independent library. We are just mapping the stuff we use so far but with time it will totally makes sense to have that separate.

**Comment by theRemix** [comment]
good idea, i've so far been using haxe-js-kit  
https://github.com/clemos/haxe-js-kit  

maybe use as a starting point?

**Comment by fponticelli** [comment]
@theRemix the express externs have been separated in their own library and they are now in a much better shape. Middlewares still need to be made externs.

https://github.com/abedev/hxexpress

**Comment by theRemix** [comment]
are you saying that we can add all extern classes to this repo?  
https://github.com/abedev/hxexpress

**Comment by fponticelli** [comment]
Yes, all externs that are related to express and middleware.

**Comment by fponticelli** [comment]
Many middleware have been added and new ones will be added on a per-needed basis.
