### ISSUE TITLE
Persistent storage using abe

### ISSUE THREAD

**Issue by tiagolr** [fponticelli/restx#56]
Hi, what persistent storage are you using with abe? Any recomended haxe libs or externs? I'm quite used to haxe SPODS but i guess they won't be available for nodejs target for a while.

Thanks for this lib, looks very simple and with lots of potential.

**Comment by fponticelli** [comment]
abe doesn't use any persistent storage since it tries to provide only the infrastructure. In a project, we are using SequelizeJS. It has its quirkness but seems to be ok.

**Comment by tiagolr** [comment]
That sounds awesome, i was also looking at Squelize, in the future an example showing how to work with Abe + squelize + passport would be terrific, for now I'm sticking with haxe ufront for a couple of projects. Cheers.

**Comment by fponticelli** [comment]
I will try to add examples as time permits ... no promises ;)
