### ISSUE TITLE
Type not found : TlsServerOptions

### ISSUE THREAD

**Issue by JbIPS** [fponticelli/restx#82]
When trying to compile Abe I get 

```
abe/App.hx:44: lines 44-48 : Type not found : TlsServerOptions
```

Looks like it has been replaced by `TlsCreateServerOptions` in hxnodejs. Doing this replacement made it work.

Do you want a PR?

**Comment by fponticelli** [comment]
Yes please.

**Comment by JbIPS** [comment]
My bad, it already has been corrected on git but not on haxelib :smiley:.
